### ISSUE TITLE
Migration failed for `:map` type with MyXQL adapter on MySQL 5.6

### ISSUE THREAD

**Issue by melpon** [elixir-ecto/ecto_sql#129]
### Environment

* Elixir version (elixir -v): Elixir 1.9.0 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 5.6
* Ecto version (mix deps): ecto-3.1.7, ecto_sql-3.1.6
* Database adapter and version (mix deps): myxql-0.2.6
* Operating system: macOS

### Current behavior

Migration code:

```elixir
defmodule Maptype.Repo.Migrations.MySchema do
  use Ecto.Migration

  def change do
    create table("my_schema") do
      add :data, :map
    end
  end
end
```

Migration result:

```
$ mix ecto.migrate
                                                                     
07:11:32.238 [info]  == Running 20190726220547 Maptype.Repo.Migrations.MySchema.change/0 forward
                                                                                                                                                                    
07:11:32.241 [info]  create table my_schema                                                                                                                         
** (MyXQL.Error) (1064) (ER_PARSE_ERROR) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to
 use near 'json, PRIMARY KEY (`id`)) ENGINE = INNODB' at line 1                                    
    (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1                                                                               
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2                  
    (ecto_sql) lib/ecto/adapters/sql.ex:708: Ecto.Adapters.SQL.execute_ddl/4         
    (ecto_sql) lib/ecto/migration/runner.ex:340: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql) lib/ecto/migration/runner.ex:119: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migration/runner.ex:118: Ecto.Migration.Runner.flush/0                                                                                      
    (stdlib) timer.erl:166: :timer.tc/1 
```

### Expected behavior

```
$ mix ecto.migrate

07:22:34.961 [info]  == Running 20190726220547 Maptype.Repo.Migrations.MySchema.change/0 forward

07:22:34.965 [info]  create table my_schema

07:22:34.979 [info]  == Migrated 20190726220547 in 0.0s
```

Ecto.Adapters.MyXQL is using a json SQL data type for a `:map` type, but MySQL 5.6 or lower does not support a json SQL data type.
Ecto.Adapters.MySQL had pass this migration file. the adapter had use a text SQL data type for a `:map` type.

**Comment by josevalim** [comment]
Yes, it is a change we did in Ecto 3. We now use the offiicial JSON support. If you want to keep it as a text because you can't upgrade, then you can define a custom type that does the encoding/decoding for you.

**Comment by melpon** [comment]
I will define a custom type. Thank you for quick reply!
