### ISSUE TITLE
bigint seems to be treated like float

### ISSUE THREAD

**Issue by mayel** [elixir-ecto/ecto_sql#233]
### Environment

* Elixir version (elixir -v): :1.10.2
* Database and version: PostgreSQL 9.6
* Ecto version (mix deps): 3.4
* Database adapter and version (mix deps): ecto_sql 3.4
* Operating system: Alpine

### Current behavior

Using Ecto to query a `bigint` field, I get this error:

```
%ArgumentError{message: "cannot load `1213.0` as type :integer for field :speakers_mil in %Locales.Language{__meta__: #Ecto.Schema.Metadata<:loaded, \"languages\">, id: nil, language_type: nil, main_country_id: nil, main_name: nil, native_name: nil, parent_language_id: nil, rtl: nil, speakers_mil: nil, speakers_native: nil, speakers_native_total: nil, sub_name: nil}"}
    (ecto 3.4.4) lib/ecto/repo/queryable.ex:386: Ecto.Repo.Queryable.struct_load!/6
    (ecto 3.4.4) lib/ecto/repo/queryable.ex:210: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
    (elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ecto 3.4.4) lib/ecto/repo/queryable.ex:197: Ecto.Repo.Queryable.execute/4
    (ecto 3.4.4) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.4.4) lib/ecto/adapters/sql.ex:875: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.2.2) lib/db_connection.ex:1427: DBConnection.run_transaction/4
```

### Expected behavior

Get back an integer.

**Comment by josevalim** [comment]
Can you please provide more information to reproduce the error? In particular, please include your migrations and make sure that the database type is bigint and not float.

**Comment by mayel** [comment]
You replied too quick! :D After double checking I mixed up a `double` field with another `bigint` one... Sorry!
