### ISSUE TITLE
 cannot reverse migration command: drop/create constraint

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto_sql#299]
### Environment
* Ecto version (mix deps):  ecto 3.5.5, ecto_sql: 3.5.3
* Database adapter and version (mix deps): postgrex 0.15.7

### Current behavior
when I try to rollback migration where `drop constraint(...)` is used, then the following error is raised
```
** (Ecto.MigrationError) cannot reverse migration command: drop constraint constraint_name from table table_name. You will need to explicitly define up/0 and down/0 in your migration
    (ecto_sql 3.5.3) lib/ecto/migration/runner.ex:213: Ecto.Migration.Runner.execute_in_direction/5
    (ecto_sql 3.5.3) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.5.3) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (ecto_sql 3.5.3) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
    (stdlib 3.12.1) timer.erl:166: :timer.tc/1
    (ecto_sql 3.5.3) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
    (ecto_sql 3.5.3) lib/ecto/migrator.ex:349: Ecto.Migrator.attempt/8
    (ecto_sql 3.5.3) lib/ecto/migrator.ex:284: anonymous fn/5 in Ecto.Migrator.do_down/5
    (ecto_sql 3.5.3) lib/ecto/migrator.ex:331: anonymous fn/3 in Ecto.Migrator.run_maybe_in_transaction/6
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:1027: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.3.1) lib/db_connection.ex:1444: DBConnection.run_transaction/4
    (ecto_sql 3.5.3) lib/ecto/migrator.ex:330: Ecto.Migrator.run_maybe_in_transaction/6
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### Expected behavior
No need to explicitly define up/down function for this command. Current workaround is to create/drop constraint using plain sql via `execute`. Is this command not supported intentionally?

**Comment by josevalim** [comment]
The issue is that dropping a constraint requires only its name and not all the steps necessary to create it. So we could improve it if we have the whole constraint definition, but we would need to check for that. A PR would be welcome!
