### ISSUE TITLE
function Ecto.Adapters.MyXQL.insert_all/7 is undefined or private

### ISSUE THREAD

**Issue by pierot** [elixir-ecto/ecto_sql#317]
### Environment

* Elixir version (elixir -v): `1.11.3`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `MySQL 8.0.23`
* Ecto version (mix deps): `3.6.0`
* Database adapter and version (mix deps): `myxql 0.4.5`
* Operating system: `MacOS`

### Current behavior

```elixir
     ** (UndefinedFunctionError) function Ecto.Adapters.MyXQL.insert_all/7 is undefined or private. Did you mean one of:

           * insert_all/8

     stacktrace:
       (ecto_sql 3.6.0) Ecto.Adapters.MyXQL.insert_all(%{cache: #Reference<0.755504238.576847873.231516>, opts: [timeout: 15000, pool_size: 10, pool: DBConnection.Ownership, ownership_timeout: :infinity], pid: #PID<0.5759.0>, repo: Menage.Repo, sql: Ecto.Adapters.MyXQL.Connection, telemetry: {XXX.Repo, :debug, [:xxx, :repo, :query]}}, %{autogenerate_id: nil, context: nil, prefix: nil, schema: nil, source: "XXX"}, [:family_id, :user_id], [[family_id: 14502, user_id: 39944]], {:raise, [], []}, [], [])
       (ecto 3.5.8) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6
       (ecto 3.5.8) lib/ecto/association.ex:1222: Ecto.Association.ManyToMany.on_repo_change/5
       (ecto 3.5.8) lib/ecto/association.ex:476: anonymous fn/8 in Ecto.Association.on_repo_change/7
       (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.5.8) lib/ecto/association.ex:472: Ecto.Association.on_repo_change/7
       (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.5.8) lib/ecto/association.ex:436: Ecto.Association.on_repo_change/4
       (ecto 3.5.8) lib/ecto/repo/schema.ex:797: Ecto.Repo.Schema.process_children/5
       (ecto 3.5.8) lib/ecto/association.ex:984: Ecto.Association.BelongsTo.on_repo_change/5
       (ecto 3.5.8) lib/ecto/association.ex:458: Ecto.Association.on_repo_change/7
       (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.5.8) lib/ecto/association.ex:436: Ecto.Association.on_repo_change/4
       (ecto 3.5.8) lib/ecto/repo/schema.ex:771: Ecto.Repo.Schema.process_parents/4
       (ecto 3.5.8) lib/ecto/repo/schema.ex:242: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto 3.5.8) lib/ecto/association.ex:984: Ecto.Association.BelongsTo.on_repo_change/5
       (ecto 3.5.8) lib/ecto/association.ex:458: Ecto.Association.on_repo_change/7
       (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.5.8) lib/ecto/association.ex:436: Ecto.Association.on_repo_change/4
       (ecto 3.5.8) lib/ecto/repo/schema.ex:771: Ecto.Repo.Schema.process_parents/4

```

After downgrading and fixating `ecto_sql` to `3.5.4` everything works as expected.

**Comment by wojtekmach** [comment]
I noticed you were running ecto 3.5.8, could you try it with ecto 3.6.x?

**Comment by josevalim** [comment]
Yes, as @wojtekmach said, something wrong happened with your build, given ecto_sql requires ecto ~> 3.6.0 and you are using ecto 3.5. Removing _build or forcing an update of Ecto should fix it. :)

**Comment by pierot** [comment]
You are correct. We had `{:ecto, "~> 3.5.0", override: true}` in our mix.exs. This prevented `ecto` from updating as wel.. That must have been a left over of a previous conflict, can't remember.
But this is definitely fixed.
