### ISSUE TITLE
ConnectionError after upgrading 

### ISSUE THREAD

**Issue by amarandon** [elixir-ecto/ecto_sql#329]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.1 (compiled with Erlang/OTP 22)
```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

PostgreSQL 11.6 (Azure Database for PostgreSQL server)

* Ecto version (mix deps):
```
* ecto 3.6.2 (Hex package) (mix)
  locked at 3.6.2 (ecto) efad6dfb
* ecto_sql 3.6.2 (Hex package) (mix)
  locked at 3.6.2 (ecto_sql) 5ec9d7e6
```
* Database adapter and version (mix deps):
```
* postgrex 0.15.9 (Hex package) (mix)
  locked at 0.15.9 (postgrex) 61071910
```
* Operating system:

Debian 9.12

### Current behavior
Since upgrading from ecto_sql 3.5.3 to ecto_sql 3.6.2 (and ecto 3.5.5 to ecto  3.6.2) we very often get this type of error when running our migrations:

```
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2994ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (albeit it increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:848: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.6.2) lib/ecto/migrator.ex:645: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.6.2) lib/ecto/migrator.ex:473: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.6.2) lib/ecto/migrator.ex:388: Ecto.Migrator.run/4
    (elixir 1.12.0) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (manager 0.1.0) lib/manager/release_tasks.ex:68: anonymous fn/2 in Manager.ReleaseTasks.run_migrations/0
make: *** [Makefile:73: migrate] Error 1
```

It's not predictable, sometimes it works, sometimes it doesn't. I've noticed there was a [change related to migrations introduced in version 3.6.0](https://github.com/elixir-ecto/ecto_sql/blob/master/CHANGELOG.md#v360-2021-04-03) so I'm wondering if our issue might be related. Interestingly this never happened with our staging server (which is less busy), only with our production server.

### Expected behavior

We'd expect migrations to work every time as it did before the upgrade.

**Comment by josevalim** [comment]
@amarandon are you using tasks or concurrency in any of your migrations? Can you also try `pool_size: 4` as the third argument when calling `with_repo` in your release tasks?

The error means we can't checkout a connection but there should only be two processes ever using connections during migrations.... unless you are running migrations while your app is running? (i.e. you are starting your application with workers and other stuff while you run migrations). Maybe you can paste your release_tasks?

**Comment by amarandon** [comment]
@josevalim I realize our release_tasks might be a bit outdated compared with the [example currently available the phoenix docs](https://hexdocs.pm/phoenix/releases.html#ecto-migrations-and-custom-commands). We start the whole app, which is probably not necessary and as you guessed starts a bunch of processes that need to connect to the database.

```elixir
defmodule Manager.ReleaseTasks do
  @moduledoc """
  Set of tasks that can be run in the context of releases.
  """
  @doc """
  Adapted from https://hexdocs.pm/distillery/running-migrations.html
  """
  @apps [:manager]

  @start_apps [
    :crypto,
    :ssl,
    :postgrex,
    :ecto,
    :ecto_sql,
    :manager
  ]

  def repos(app), do: Application.fetch_env!(app, :ecto_repos)

  def migrate do
    start_services()

    run_migrations()

    stop_services()
  end

  def start_services do
    for app <- @apps do
      IO.puts("Starting dependencies..")
      # Start apps necessary for executing migrations
      Enum.each(@start_apps, &Application.ensure_all_started/1)

      # Start the Repo(s) for app
      IO.puts("Starting repos..")
      Enum.each(repos(app), & &1.start_link(pool_size: 2))
    end
  end

  def stop_services do
    :init.stop()
  end

  defp run_migrations() do
    IO.puts("Running migrations..")

    for app <- @apps do
      Enum.each(repos(app), &run_migrations_for/1)
    end
  end

  defp run_migrations_for(repo) do
    app = Keyword.get(repo.config, :otp_app)
    IO.puts("Running migrations for #{app}..")
    migrations_path = priv_path_for(repo, "migrations")
    Ecto.Migrator.run(repo, migrations_path, :up, all: true)
  end

  def priv_path_for(repo, filename) do
    app = Keyword.get(repo.config, :otp_app)
    repo_underscore = repo |> Module.split() |> List.last() |> Macro.underscore()
    Path.join([priv_dir(app), repo_underscore, filename])
  end

  def priv_dir(app), do: "#{:code.priv_dir(app)}"
end
```
