### ISSUE TITLE
truncated error message: disconnected: ** (DBConnection.ConnectionError) owner #PID<*.*.*> exited

### ISSUE THREAD

**Issue by ruslandoga** [elixir-ecto/ecto_sql#359]
👋

### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 24 [erts-12.1.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

```
docker:gangstead/postgis:13-arm (server 13.1 (Debian 13.1-1.pgdg100+1))
```

* Ecto version (mix deps):

```
3.7.1
```

* Database adapter and version (mix deps):

```
postgrex 0.15.13
```

* Operating system:
```
macos 11.6 (20G165)
```

### Current behavior

Repro: https://github.com/ruslandoga/ecto_error

When running `mix test` with `ecto_sql 3.7.1`, I'm sometimes getting what seems to be a truncated error message:

```elixir
17:09:19.897 [error] Postgrex.Protocol (#PID<0.253.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.286.0> exited
```

for this contrived test:

https://github.com/ruslandoga/ecto_error/blob/120fba5cb603bf543d745fbc6815ea12b2752a31/test/ecto_error_test.exs#L12-L26

And sometimes I'm getting the full error message as shown below.

But in the "real" app where the repo is being used from a phoenix channel after receiving a broadcast at the end of the test I'm only getting the truncated error version. I can update my repro repo to include a phoenix channels test more similar to my actual issue if needed.

### Expected behavior

I expect the error message to include the helpful `Client #PID<0.291.0> is still using a connection from owner at location:` part:

```elixir
[error] Postgrex.Protocol (#PID<0.255.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.286.0> exited

Client #PID<0.291.0> is still using a connection from owner at location:

    :prim_inet.recv0/3
    (postgrex 0.15.13) lib/postgrex/protocol.ex:2996: Postgrex.Protocol.msg_recv/4
    (postgrex 0.15.13) lib/postgrex/protocol.ex:2042: Postgrex.Protocol.recv_bind/3
    (postgrex 0.15.13) lib/postgrex/protocol.ex:1967: Postgrex.Protocol.bind_execute/4
    (ecto_sql 3.6.2) lib/ecto/adapters/sql/sandbox.ex:372: Ecto.Adapters.SQL.Sandbox.Connection.proxy/3
    (db_connection 2.4.1) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.1) lib/db_connection.ex:1333: DBConnection.run_execute/5
    (db_connection 2.4.1) lib/db_connection.ex:1428: DBConnection.run/6
    (db_connection 2.4.1) lib/db_connection.ex:593: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.1) lib/db_connection.ex:585: DBConnection.prepare_execute/4
    (postgrex 0.15.13) lib/postgrex.ex:313: Postgrex.query_prepare_execute/4
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:367: Ecto.Adapters.SQL.query!/4

The connection itself was checked out by #PID<0.291.0> at location:

    (postgrex 0.15.13) lib/postgrex.ex:313: Postgrex.query_prepare_execute/4
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:367: Ecto.Adapters.SQL.query!/4
```

**Comment by ruslandoga** [comment]
https://gist.github.com/ruslandoga/e8b5d228bc4514b2a206039320744e59 shows a few runs with the following deps

```elixir
%{
  "connection": {:hex, :connection, "1.1.0", "ff2a49c4b75b6fb3e674bfc5536451607270aac754ffd1bdfe175abe4a6d7a68", [:mix], [], "hexpm", "722c1eb0a418fbe91ba7bd59a47e28008a189d47e37e0e7bb85585a016b2869c"},
  "db_connection": {:hex, :db_connection, "2.4.1", "6411f6e23f1a8b68a82fa3a36366d4881f21f47fc79a9efb8c615e62050219da", [:mix], [{:connection, "~> 1.0", [hex: :connection, repo: "hexpm", optional: false]}, {:telemetry, "~> 0.4 or ~> 1.0", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm", "ea36d226ec5999781a9a8ad64e5d8c4454ecedc7a4d643e4832bf08efca01f00"},
  "decimal": {:hex, :decimal, "2.0.0", "a78296e617b0f5dd4c6caf57c714431347912ffb1d0842e998e9792b5642d697", [:mix], [], "hexpm", "34666e9c55dea81013e77d9d87370fe6cb6291d1ef32f46a1600230b1d44f577"},
  "ecto": {:hex, :ecto, "3.7.1", "a20598862351b29f80f285b21ec5297da1181c0442687f9b8329f0445d228892", [:mix], [{:decimal, "~> 1.6 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:telemetry, "~> 0.4 or ~> 1.0", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm", "d36e5b39fc479e654cffd4dbe1865d9716e4a9b6311faff799b6f90ab81b8638"},
  "ecto_sql": {:hex, :ecto_sql, "3.7.1", "8de624ef50b2a8540252d8c60506379fbbc2707be1606853df371cf53df5d053", [:mix], [{:db_connection, "~> 2.2", [hex: :db_connection, repo: "hexpm", optional: false]}, {:ecto, "~> 3.7.0", [hex: :ecto, repo: "hexpm", optional: false]}, {:myxql, "~> 0.4.0 or ~> 0.5.0", [hex: :myxql, repo: "hexpm", optional: true]}, {:postgrex, "~> 0.15.0 or ~> 1.0", [hex: :postgrex, repo: "hexpm", optional: true]}, {:tds, "~> 2.1.1 or ~> 2.2", [hex: :tds, repo: "hexpm", optional: true]}, {:telemetry, "~> 0.4.0 or ~> 1.0", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm", "2b42a32e2ce92f64aba5c88617891ab3b0ba34f3f3a503fa20009eae1a401c81"},
  "postgrex": {:hex, :postgrex, "0.15.13", "7794e697481799aee8982688c261901de493eb64451feee6ea58207d7266d54a", [:mix], [{:connection, "~> 1.0", [hex: :connection, repo: "hexpm", optional: false]}, {:db_connection, "~> 2.1", [hex: :db_connection, repo: "hexpm", optional: false]}, {:decimal, "~> 1.5 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "3ffb76e1a97cfefe5c6a95632a27ffb67f28871c9741fb585f9d1c3cd2af70f1"},
  "telemetry": {:hex, :telemetry, "1.0.0", "0f453a102cdf13d506b7c0ab158324c337c41f1cc7548f0bc0e130bbf0ae9452", [:rebar3], [], "hexpm", "73bc09fa59b4a0284efb4624335583c528e07ec9ae76aca96ea0673850aec57a"},
}
```

**Comment by josevalim** [comment]
Hi @ruslandoga 👋 

Yes, it is a race condition. We show the stacktrace and related information if the process are available and if the process happens to be using the connection. But you may be either before or after those events, in which case the connection process has "nothing" to show.

If you generate a new app with Phoenix v1.6, check out the new way it starts the owner, it should be more resilient to cases like yours. If the issue still persists, please open up an issue on Phoenix with the channel test example and copy me. I can take a look there, but it isn't an Ecto issue. :)

**Comment by josevalim** [comment]
@ruslandoga I can see that you are already using start_owner and stop_owner, so I think the issue with the channel likely still exists. I am investigating.

**Comment by josevalim** [comment]
Can you please try Phoenix master?

**Comment by ruslandoga** [comment]
@josevalim 

Before using master:

```elixir
> mix test

...************..............................***.........................................................*.........................14:55:20.124 [error] Postgrex.Protocol (#PID<0.570.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1343.0> exited
..................

  1) test more with active users more than count (TWeb.FeedChannelTest)
     test/t_web/channels/feed_channel_test.exs:231
     Assertion with == failed
     code:  assert feed == [%{"distance" => 9510, "profile" => %{user_id: m1.id, name: "mate-1", gender: "F", story: [%{"background" => %{"proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q", "s3_key" => "test"}, "labels" => []}]}}, %{"distance" => 9510, "profile" => %{user_id: m2.id, name: "mate-2", gender: "N", story: [%{"background" => %{"proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q", "s3_key" => "test"}, "labels" => []}]}}]
     left:  [
              %{"distance" => 9510, "profile" => %{gender: "N", name: "mate-2", story: [%{"background" => %{"proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q", "s3_key" => "test"}, "labels" => []}], user_id: "0000017d-0a58-a2eb-1e00-8a0e24440000"}},
              %{
                "distance" => 9510,
                "profile" => %{
                  gender: "F",
                  name: "mate-1",
                  story: [
                    %{
                      "background" => %{
                        "proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q",
                        "s3_key" => "test"
                      },
                      "labels" => []
                    }
                  ],
                  user_id: "0000017d-0a58-a2e4-1e00-8a0e24440000"
                }
              }
            ]
     right: [
              %{
                "distance" => 9510,
                "profile" => %{
                  gender: "F",
                  name: "mate-1",
                  story: [
                    %{
                      "background" => %{
                        "proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q",
                        "s3_key" => "test"
                      },
                      "labels" => []
                    }
                  ],
                  user_id: "0000017d-0a58-a2e4-1e00-8a0e24440000"
                }
              },
              %{"distance" => 9510, "profile" => %{gender: "N", name: "mate-2", story: [%{"background" => %{"proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q", "s3_key" => "test"}, "labels" => []}], user_id: "0000017d-0a58-a2eb-1e00-8a0e24440000"}}
            ]
     stacktrace:
       test/t_web/channels/feed_channel_test.exs:266: (test)

..

Finished in 2.5 seconds (2.4s async, 0.03s sync)
13 doctests, 139 tests, 1 failure, 16 skipped

Randomized with seed 335055
```

Using `{:phoenix, github: "phoenixframework/phoenix", override: true},`:

```elixir
mix test
...************..................................***.......................................14:56:56.729 [error] Process #PID<0.1076.0> raised an exception
** (ArgumentError) fetch_test_supervisor!/0 can only be invoked from the test process
    (phoenix 1.6.2) lib/phoenix/test/channel_test.ex:413: Phoenix.ChannelTest.fetch_test_supervisor!/0
    (phoenix 1.6.2) lib/phoenix/test/channel_test.ex:388: anonymous fn/4 in Phoenix.ChannelTest.join/4
    (phoenix 1.6.2) lib/phoenix/channel/server.ex:28: Phoenix.Channel.Server.join/4
    (phoenix 1.6.2) lib/phoenix/test/channel_test.ex:391: Phoenix.ChannelTest.join/4
    test/t_web/channels/call_channel_test.exs:254: anonymous fn/4 in TWeb.CallChannelTest."test presence receives presence_state and presence_diff on join/leave"/1
...............*................

  1) test more with active users more than count (TWeb.FeedChannelTest)
     test/t_web/channels/feed_channel_test.exs:231
     Assertion with == failed
     code:  assert feed == [%{"distance" => 9510, "profile" => %{user_id: m1.id, name: "mate-1", gender: "F", story: [%{"background" => %{"proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q", "s3_key" => "test"}, "labels" => []}]}}, %{"distance" => 9510, "profile" => %{user_id: m2.id, name: "mate-2", gender: "N", story: [%{"background" => %{"proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q", "s3_key" => "test"}, "labels" => []}]}}]
     left:  [
              %{"distance" => 9510, "profile" => %{gender: "M", name: "mate-3", story: [%{"background" => %{"proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q", "s3_key" => "test"}, "labels" => []}], user_id: "0000017d-0a5a-1c28-1e00-8a0e24440000"}},
              %{
                "distance" => 9510,
                "profile" => %{
                  gender: "F",
                  name: "mate-1",
                  story: [
                    %{
                      "background" => %{
                        "proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q",
                        "s3_key" => "test"
                      },
                      "labels" => []
                    }
                  ],
                  user_id: "0000017d-0a5a-1c1c-1e00-8a0e24440000"
                }
              }
            ]
     right: [
              %{
                "distance" => 9510,
                "profile" => %{
                  gender: "F",
                  name: "mate-1",
                  story: [
                    %{
                      "background" => %{
                        "proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q",
                        "s3_key" => "test"
                      },
                      "labels" => []
                    }
                  ],
                  user_id: "0000017d-0a5a-1c1c-1e00-8a0e24440000"
                }
              },
              %{"distance" => 9510, "profile" => %{gender: "N", name: "mate-2", story: [%{"background" => %{"proxy" => "https://d1234.cloudfront.net/1hPLj5rf4QOwpxjzZB_S-X9SsrQMj0cayJcOCmnvXz4/fit/1000/0/sm/0/aHR0cHM6Ly9wcmV0ZW5kLXRoaXMtaXMtcmVhbC5zMy5hbWF6b25hd3MuY29tL3Rlc3Q", "s3_key" => "test"}, "labels" => []}], user_id: "0000017d-0a5a-1c22-1e00-8a0e24440000"}}
            ]
     stacktrace:
       test/t_web/channels/feed_channel_test.exs:266: (test)

............

  2) test presence receives presence_state and presence_diff on join/leave (TWeb.CallChannelTest)
     test/t_web/channels/call_channel_test.exs:227
     Assertion failed, no matching message after 1000ms
     The process mailbox is empty.
     code: assert_receive %Phoenix.Socket.Broadcast{event: "presence_diff", payload: %{joins: joins, leaves: leaves}}
     stacktrace:
       test/t_web/channels/call_channel_test.exs:288: (test)

...14:56:57.772 [error] Postgrex.Protocol (#PID<0.574.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1468.0> exited
............

Finished in 2.4 seconds (2.3s async, 0.04s sync)
13 doctests, 139 tests, 2 failures, 16 skipped

Randomized with seed 662000
```

**Comment by ruslandoga** [comment]
The failing test seems to only fail when there is `14:55:20.124 [error] Postgrex.Protocol (#PID<0.570.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1343.0> exited` as if this failure makes some change in postgres row order (the failing test is not using an explicit `order_by` to fetch the "profiles")

**Comment by josevalim** [comment]
@ruslandoga so part of the issue seems to be you are joining a channel for tests outside of the test process. If you fix that, master will at least guarantee a proper shutdown ordering (i.e. the channel will be shutdown before the connection owner).

**Comment by ruslandoga** [comment]
@josevalim only the presence test uses "external" process, I'll fix that. The test causing `14:56:57.772 [error] Postgrex.Protocol (#PID<0.574.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1468.0> exited` is using the test process though.

**Comment by josevalim** [comment]
Right, any process that you spawn in your tests that are not under the test supervisor will shutdown after the connection, which will lead to such errors. The commit to latest Phoenix addresses this issue for channels. For presence, you need to ask the presence tasks to terminate: https://hexdocs.pm/phoenix/Phoenix.Presence.html#module-testing-with-presence

and similar to an other process that may be involved. :)

**Comment by ruslandoga** [comment]
@josevalim I've opened an issue in phx repo https://github.com/phoenixframework/phoenix/issues/4590
