### ISSUE TITLE
Calling a mysql stored procedure which includes transactions causes a case clause error

### ISSUE THREAD

**Issue by wizardfrag** [elixir-ecto/ecto_sql#37]
### Environment

* Elixir version: **Elixir 1.7.3 (compiled with Erlang/OTP 21)**
* Phoenix version: **1.4.0**
* Database and version: **MariaDB 10.3.10**
* Ecto version: **ecto 3.0.1, ecto_sql 3.0.0**
* Database adapter and version: **mariaex 0.9.9**
* Operating system: **macOS 10.14**

### Current behavior

Running the following as part of a phoenix conn test using MyappWeb.ConnCase causes the test to pass, but the exception is printed to the terminal after the test has completed. I believe it could be something to do with the `COMMIT` inside the stored procedure.

stored procedure:
```sql
create table db_test
(
  id    int auto_increment
    primary key,
  `key` varchar(32) default 'NULL' null,
  val   text default 'NULL'        null
);


create procedure db_test(IN inKey varchar(32), IN inVal text)
  BEGIN
    START TRANSACTION;
    INSERT INTO db_test (`key`, val) VALUES (inKey, inVal);
    COMMIT;
  END;
```

controller:
```elixir
  def test_db(conn, _params) do
    {:ok, v} = Repo.query("CALL test.db_test('3', 'maybe')")

    json(conn, v.rows)
  end
```

exception:
```
10:02:07.200 [error] GenServer #PID<0.456.0> terminating
** (CaseClauseError) no case clause matching: {:idle, %Mariaex.Protocol{binary_as: :field_type_var_string, buffer: "", cache: #Reference<0.2931625945.744620033.246778>, catch_eof: false, connection_id: #PID<0.418.0>, cursors: %{}, datetime: :structs, deprecated_eof: true, json_library: Poison, lru_cache:{100, #Reference<0.2931625945.744620033.246779>}, opts: [socket_options: [], sock_type: :tcp, cache_size: 100, port: 3306, datetime: :structs, repo: Myapp.Repo, telemetry_prefix: [:myapp, :repo], otp_app: :myapp, timeout: 15000, pool_timeout: 5000, pool_size: 10, username: "xxxx", password: "xxxx", database: "myapp_test", hostname: "localhost"], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.82>}, ssl_conn_state: :not_used, state: :running, state_data: nil, timeout: 15000, transaction_status: :idle}}
    (ecto_sql) lib/ecto/adapters/sql/sandbox.ex:514: Ecto.Adapters.SQL.Sandbox.pre_checkin/4
    (db_connection) lib/db_connection/ownership/proxy.ex:210: DBConnection.Ownership.Proxy.pool_done/5
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.2931625945.744488961.246901>, :process, #PID<0.455.0>, :shutdown}
10:02:07.200 [error] Mariaex.Protocol (#PID<0.418.0>) disconnected: ** (DBConnection.ConnectionError)client #PID<0.456.0> exited
```

### Expected behavior

The test will pass and no error will be printed to the console. As happened with Ecto 2 / Phoenix 1.3.4.

**Comment by josevalim** [comment]
Thanks @wizardfrag! Since this is a bit more ellaborate to reproduce than I imagined, can you please push a small repository to github that makes it straight-forward to reproduce? Let me know if you have any questions, thanks!
