### ISSUE TITLE
(CaseClauseError) no case clause matching: nil in `Ecto.Adapters.Postgres.Connection`

### ISSUE THREAD

**Issue by sabit990928** [elixir-ecto/ecto_sql#395]
### Environment

* Elixir version (elixir -v): 1.7
* Ecto version: `master`

### Current behavior
dependabot recommended to update `ecto_sql` from 3.6.2 to 3.8.0. Then bunch of my local tests failed with following error: 
```elixir
     ** (CaseClauseError) no case clause matching: nil
     stacktrace:
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:1267: Ecto.Adapters.Postgres.Connection.get_parent_sources_ix/2
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:618: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:734: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:609: Ecto.Adapters.Postgres.Connection.paren_expr/3
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:734: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:609: Ecto.Adapters.Postgres.Connection.paren_expr/3
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:589: Ecto.Adapters.Postgres.Connection.boolean/4
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:137: Ecto.Adapters.Postgres.Connection.all/2
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:662: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:645: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:734: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:609: Ecto.Adapters.Postgres.Connection.paren_expr/3
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:591: anonymous fn/4 in Ecto.Adapters.Postgres.Connection.boolean/4
       (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:589: Ecto.Adapters.Postgres.Connection.boolean/4
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres/connection.ex:137: Ecto.Adapters.Postgres.Connection.all/2
       (ecto_sql 3.8.0) lib/ecto/adapters/postgres.ex:106: Ecto.Adapters.Postgres.prepare/2
       (ecto 3.6.2) lib/ecto/query/planner.ex:180: Ecto.Query.Planner.query_without_cache/4
       (ecto 3.6.2) lib/ecto/query/planner.ex:150: Ecto.Query.Planner.query_prepare/6
       (ecto 3.6.2) lib/ecto/query/planner.ex:125: Ecto.Query.Planner.query_with_cache/7
```

**Comment by josevalim** [comment]
You are mixing ecto 3.6 with ecto_sql 3.8, probably because of an `override` somewhere. Make sure you are also using ecto 3.8.1.

**Comment by sabit990928** [comment]
Ok, will have a look. Thank you
