### ISSUE TITLE
mix ecto.migrate -r Repo <- doesn't work

### ISSUE THREAD

**Issue by ValMilkevich** [elixir-ecto/ecto_sql#437]
### Elixir version

1.12

### Database and Version

PostgreSQL 9.4

### Ecto Versions

3.8.3

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Actual Error when calling mix.ecto.migrate -r Repo

** (FunctionClauseError) no function clause matching in Ecto.Repo.Queryable.execute/4

    The following arguments were given to Ecto.Repo.Queryable.execute/4:

        # 1
        :all

        # 2
        SolarData.Repo

        # 3
        #Ecto.Query<from s0 in "schema_migrations", select: type(s0.version, :integer)>

        # 4
        [prefix: nil, timeout: :infinity, log: false, schema_migration: true]

    Attempted function clauses (showing 1 out of 1):

        defp execute(operation, name, query, {adapter_meta, opts} = tuplet)

    (ecto 3.8.4) Ecto.Repo.Queryable.execute/4
    (ecto 3.8.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto_sql 3.8.3) lib/ecto/migrator.ex:533: anonymous fn/5 in Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4

### My investigation leads to wrong return from `SchemaMigration.versions(repo,` config, opts[:prefix])`

ecto_sql/lib/ecto/migrator.ex:515 
{migration_repo, query, all_opts} = SchemaMigration.versions(repo, config, opts[:prefix])

all_opts are like: [prefix: %{}, timeout: :infinity, log: false, schema_migration: true]

migrator.ex 532-534
migration_repo.__adapter__().lock_for_migrations(meta, opts, fn ->
            fun.(config, migration_repo.all(query, all_opts))
          end)

Now Ecto 3.8.3
ecto/lib/ecto/repo/queryable.ex: 13

  def all(name, queryable, tuplet) do
    query =
      queryable
      |> Ecto.Queryable.to_query()
      |> Ecto.Query.Planner.ensure_select(true)

    execute(:all, name, query, tuplet) |> elem(1)
  end
  
> expects tuplet, and is given: [prefix: %{}, timeout: :infinity, log: false, schema_migration: true]

          
          

### Expected behavior

`{_,_, all_opts} = SchemaMigration.versions(repo,` config, opts[:prefix])` 

`all_opts` should be consumable by `Ecto.Repo.Queryable.all(name, queryable, tuplet)`

**Comment by josevalim** [comment]
It seems a stale cache issue. Please remove `_build` and try again.
